/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { EventFragment } from "@ethersproject/abi"
import type { Listener, Provider } from "@ethersproject/providers"
import type { BaseContract, BigNumber, Signer, utils } from "ethers"
import type { OnEvent, TypedEvent, TypedEventFilter, TypedListener } from "./common"

export interface IEternisTipPostDBInterface extends utils.Interface {
	functions: {}

	events: {
		"EternisPost(uint256,bytes)": EventFragment
		"EternisTip(uint256,address)": EventFragment
	}

	getEvent(nameOrSignatureOrTopic: "EternisPost"): EventFragment
	getEvent(nameOrSignatureOrTopic: "EternisTip"): EventFragment
}

export interface EternisPostEventObject {
	postIndex: BigNumber
	postData: string
}
export type EternisPostEvent = TypedEvent<[BigNumber, string], EternisPostEventObject>

export type EternisPostEventFilter = TypedEventFilter<EternisPostEvent>

export interface EternisTipEventObject {
	postIndex: BigNumber
	tipTo: string
}
export type EternisTipEvent = TypedEvent<[BigNumber, string], EternisTipEventObject>

export type EternisTipEventFilter = TypedEventFilter<EternisTipEvent>

export interface IEternisTipPostDB extends BaseContract {
	connect(signerOrProvider: Signer | Provider | string): this
	attach(addressOrName: string): this
	deployed(): Promise<this>

	interface: IEternisTipPostDBInterface

	queryFilter<TEvent extends TypedEvent>(
		event: TypedEventFilter<TEvent>,
		fromBlockOrBlockhash?: string | number | undefined,
		toBlock?: string | number | undefined
	): Promise<Array<TEvent>>

	listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>
	listeners(eventName?: string): Array<Listener>
	removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this
	removeAllListeners(eventName?: string): this
	off: OnEvent<this>
	on: OnEvent<this>
	once: OnEvent<this>
	removeListener: OnEvent<this>

	functions: {}

	callStatic: {}

	filters: {
		"EternisPost(uint256,bytes)"(postIndex?: null, postData?: null): EternisPostEventFilter
		EternisPost(postIndex?: null, postData?: null): EternisPostEventFilter

		"EternisTip(uint256,address)"(postIndex?: null, tipTo?: null): EternisTipEventFilter
		EternisTip(postIndex?: null, tipTo?: null): EternisTipEventFilter
	}

	estimateGas: {}

	populateTransaction: {}
}
