/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EternisPostDB } from "./EternisPostDB"
export type { EternisTipPostDB } from "./EternisTipPostDB"
export * as factories from "./factories"
export { EternisPostDB__factory } from "./factories/EternisPostDB__factory"
export { EternisTipPostDB__factory } from "./factories/EternisTipPostDB__factory"
export { IEternisPostDB__factory } from "./factories/IEternisPostDB__factory"
export { IEternisTipPostDB__factory } from "./factories/IEternisTipPostDB__factory"
export type { IEternisPostDB } from "./IEternisPostDB"
export type { IEternisTipPostDB } from "./IEternisTipPostDB"
