/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider } from "@ethersproject/providers"
import { Contract, Signer, utils } from "ethers"
import type { IEternisTipPostDB, IEternisTipPostDBInterface } from "../IEternisTipPostDB"

const _abi = [
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: "uint256",
				name: "postIndex",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "bytes",
				name: "postData",
				type: "bytes",
			},
		],
		name: "EternisPost",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: "uint256",
				name: "postIndex",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "address",
				name: "tipTo",
				type: "address",
			},
		],
		name: "EternisTip",
		type: "event",
	},
] as const

export class IEternisTipPostDB__factory {
	static readonly abi = _abi
	static createInterface(): IEternisTipPostDBInterface {
		return new utils.Interface(_abi) as IEternisTipPostDBInterface
	}
	static connect(address: string, signerOrProvider: Signer | Provider): IEternisTipPostDB {
		return new Contract(address, _abi, signerOrProvider) as IEternisTipPostDB
	}
}
