/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EternisPostDB__factory } from "./EternisPostDB__factory"
export { EternisTipPostDB__factory } from "./EternisTipPostDB__factory"
export { IEternisPostDB__factory } from "./IEternisPostDB__factory"
export { IEternisTipPostDB__factory } from "./IEternisTipPostDB__factory"
